version: '3'
services:
  db:
    image: postgres
    container_name: code-challenge-db
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  uplifty:
    build:
      context: .
      dockerfile: ./docker/Docker.server/Dockerfile
    image: code-challenge
    env_file: .env
    container_name: code-challenge
    volumes:
      - .:/code
    ports:
      - '5000:5000'
      - '3000:3000'
    depends_on:
      - db
    links:
      - db:postgres
